# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_zdlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zdlistForm(object):
    def setupUi(self, zdlistForm):
        zdlistForm.setObjectName("zdlistForm")
        zdlistForm.resize(212, 261)
        zdlistForm.setStyleSheet("\n"
"#tabZDlist::pane{    \n"
"    border: none;\n"
"}\n"
"#tabZDlist{  \n"
"    border: none;\n"
"    background: transparent;    \n"
"}\n"
"QToolTip{\n"
"border: 2px solid qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));   \n"
"    background-color: rgb(22,26,32);\n"
"    ridge:ridge;\n"
"    padding: 4px;\n"
"    border-radius:10px;\n"
"}\n"
" \n"
"\n"
"QCheckBox::indicator:unchecked\n"
"{\n"
"image:url(data/img/SrvSta3.png);\n"
"}\n"
"QCheckBox::indicator:checked\n"
"{\n"
"image:url(data/img/SrvSta1.png);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(zdlistForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabZDlist = QtWidgets.QTableWidget(zdlistForm)
        self.tabZDlist.setObjectName("tabZDlist")
        self.tabZDlist.setColumnCount(2)
        self.tabZDlist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabZDlist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabZDlist.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tabZDlist)

        self.retranslateUi(zdlistForm)
        QtCore.QMetaObject.connectSlotsByName(zdlistForm)

    def retranslateUi(self, zdlistForm):
        _translate = QtCore.QCoreApplication.translate
        zdlistForm.setWindowTitle(_translate("zdlistForm", "Form"))
        item = self.tabZDlist.horizontalHeaderItem(0)
        item.setText(_translate("zdlistForm", "英雄名"))
        item = self.tabZDlist.horizontalHeaderItem(1)
        item.setText(_translate("zdlistForm", "自动"))
