# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_strategy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_strategyForm(object):
    def setupUi(self, strategyForm):
        strategyForm.setObjectName("strategyForm")
        strategyForm.resize(504, 53)
        strategyForm.setMinimumSize(QtCore.QSize(1, 1))
        strategyForm.setStyleSheet("QPushButton{\n"
"    color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"    border: 2px solid qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));   \n"
"    background-color: rgb(22,26,32);\n"
"    ridge:ridge;\n"
"    padding: 4px;\n"
"    border-radius:10px;\n"
"    \n"
"    font: 75 14pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));   \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(strategyForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_zqgd = QtWidgets.QPushButton(strategyForm)
        self.bt_zqgd.setObjectName("bt_zqgd")
        self.horizontalLayout.addWidget(self.bt_zqgd)
        self.bt_spjz = QtWidgets.QPushButton(strategyForm)
        self.bt_spjz.setObjectName("bt_spjz")
        self.horizontalLayout.addWidget(self.bt_spjz)
        self.bt_zbfx = QtWidgets.QPushButton(strategyForm)
        self.bt_zbfx.setObjectName("bt_zbfx")
        self.horizontalLayout.addWidget(self.bt_zbfx)
        self.bt_zrzw = QtWidgets.QPushButton(strategyForm)
        self.bt_zrzw.setObjectName("bt_zrzw")
        self.horizontalLayout.addWidget(self.bt_zrzw)
        self.bt_qrzd = QtWidgets.QPushButton(strategyForm)
        self.bt_qrzd.setObjectName("bt_qrzd")
        self.horizontalLayout.addWidget(self.bt_qrzd)

        self.retranslateUi(strategyForm)
        QtCore.QMetaObject.connectSlotsByName(strategyForm)

    def retranslateUi(self, strategyForm):
        _translate = QtCore.QCoreApplication.translate
        strategyForm.setWindowTitle(_translate("strategyForm", "Form"))
        self.bt_zqgd.setText(_translate("strategyForm", "早期过渡"))
        self.bt_spjz.setText(_translate("strategyForm", "搜牌节奏"))
        self.bt_zbfx.setText(_translate("strategyForm", "装备分析"))
        self.bt_zrzw.setText(_translate("strategyForm", "阵容站位"))
        self.bt_qrzd.setText(_translate("strategyForm", "确认自动"))
