Path_chess = 'data/chess/'
Path_chess_D = 'data/chess_d/'
Path_equip = 'data/equip/'
Path_job = 'data/job/'
Path_race = 'data/race/'
Path_job2 = 'data/job2/'
Path_race2 = 'data/race2/'
Path_img='data/img/'